TRAIN:
  # ENABLE: False # default True
  DATASET: ssv2
  BATCH_SIZE: 64
  EVAL_PERIOD: 2
  CHECKPOINT_PERIOD: 2
  AUTO_RESUME: True
TEST:
  ENABLE: True
  DATASET: ssv2
  BATCH_SIZE: 64
  # 6-views
  NUM_ENSEMBLE_VIEWS: 2
  NUM_SPATIAL_CROPS: 3
  # single clip & single crop
#  NUM_ENSEMBLE_VIEWS: 1
#  NUM_SPATIAL_CROPS: 1
DATA:
  NUM_FRAMES: 16
  SAMPLING_RATE: 5
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
#  DECODING_BACKEND: torchvision
  PATH_TO_DATA_DIR: /home/lsrock1/data/sth-sth-v2/20bn-something-something-v2-SF-frames
  PATH_PREFIX: /home/lsrock1/data/sth-sth-v2/20bn-something-something-v2-SF-frames
X3D:
  WIDTH_FACTOR: 2.0
  DEPTH_FACTOR: 5.0
  BOTTLENECK_FACTOR: 2.25
  DIM_C5: 2048
  DIM_C1: 12
RESNET:
  ZERO_INIT_FINAL_BN: True
  TRANS_FUNC: x3d_transform
  STRIDE_1X1: False
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
  WEIGHT_DECAY: 0.0
SOLVER:
  BASE_LR: 0.1
  LR_POLICY: cosine
  BASE_LR_SCALE_NUM_SHARDS: True
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-5
  WARMUP_EPOCHS: 1.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 174
  ARCH: x3d
  MODEL_NAME: X3D
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 8
RNG_SEED: 0
LOG_MODEL_INFO: True
OUTPUT_DIR: output/SSv2/x3d/x3d_L
